#!/usr/bin/env python3
"""
scripts/gen_iccit_configs.py — generates configs/experiment/iccit/*.yaml,
the ICCIT 2026 channel-representation study's run matrix (plan document
§3/§4): mk_unet across every channel mode (m1-m8), width-matched RGB
capacity controls (m2/m4/m5/m7), the m4/m5 order-ablation ("pre") variants,
a U-Net generality check (m1/m4/m4matched/m5), and one external-cohort
evaluation config for ColonDB.

Each file composes ``[base.yaml, dataset/<ds>.yaml, model/.../<size>.yaml]``
plus a small override block (channel_mode/channel_build_order/in_channels/
experiment_name) — the same pattern every hand-written config under
configs/experiment/ already uses. Width-matched variants additionally
search models.build.build_width_matched for an RGB channel-width whose
parameter count matches the target (non-RGB) mode's model within
tolerance; the achieved match is recorded as a documentation comment in
the generated file (orchestration.schema.Config forbids undeclared extra
top-level keys, so it can't be a YAML field — the per-run manifest is
where a real training run should record it via
orchestration.manifest.RunManifest.record(), same as any other
run-time-only fact).

This script only *generates configs* — it does not launch training. See
orchestration.runner.run_sweep for that.

Usage:
    python scripts/gen_iccit_configs.py             # write configs
    python scripts/gen_iccit_configs.py --dry-run    # print, write nothing
"""
from __future__ import annotations

import argparse
import os
import sys

import yaml

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.path.insert(0, REPO_ROOT)

from datasets.channels import effective_channel_count  # noqa: E402
from models.build import build_width_matched  # noqa: E402
from models.registry import get_model  # noqa: E402
from utils.metrics import count_parameters  # noqa: E402

OUT_DIR = os.path.join(REPO_ROOT, "configs", "experiment", "iccit")

DATASETS = ["clinicdb", "isic18", "busi"]
CHANNEL_MODES = ["m1", "m2", "m3", "m4", "m5", "m6", "m7", "m8"]
MATCHED_MODES = ["m2", "m4", "m5", "m7"]
ORDER_ABLATION_MODES = ["m4", "m5"]

# Primary MK-UNet size for the channel-mode grid: "t" — 126 MK-UNet runs
# (72 channel-mode + 36 matched-control + 18 order-ablation) across a
# 6-page paper's exploratory scope favours the fastest-to-train size, not
# a capacity race; the plan names mk_unet as "primary" without pinning a
# size.
MKUNET_SIZE = "t"
MKUNET_CHANNELS = [4, 8, 16, 24, 32]
MKUNET_KWARGS = dict(depths=[1, 1, 1, 1, 1], kernel_sizes=[1, 3, 5], expansion_factor=2, gag_kernel=3)
MKUNET_MODEL_NAME = f"mk_unet_{MKUNET_SIZE}"
MKUNET_INPUT_SHAPE_HW = (256, 256)

UNET_FEATURES = [64, 128, 256, 512]  # configs/base.yaml's default

TOL = 0.1
MODALITY = "colour"  # every configs/dataset/*.yaml fragment used here leaves
                      # dataset.modality at its schema default ("colour")


def _mkunet_model_fn(channels):
    return get_model(name=MKUNET_MODEL_NAME, in_channels=3, channels=channels, num_classes=1, **MKUNET_KWARGS)


def _mkunet_params(in_channels: int) -> int:
    m = get_model(name=MKUNET_MODEL_NAME, in_channels=in_channels, channels=MKUNET_CHANNELS,
                  num_classes=1, **MKUNET_KWARGS)
    return count_parameters(m)


def _unet_model_fn(features):
    return get_model(name="unet", in_channels=3, out_channels=1, features=features)


def _unet_params(in_channels: int) -> int:
    m = get_model(name="unet", in_channels=in_channels, out_channels=1, features=UNET_FEATURES)
    return count_parameters(m)


def _match_rgb_width(model_fn, width_candidates, target_params: int) -> dict:
    return build_width_matched(
        base_model_fn=model_fn,
        width_candidates=width_candidates,
        input_shape=(3, *MKUNET_INPUT_SHAPE_HW),
        target_params=target_params,
        tol=TOL,
    )


def _header(lines) -> str:
    return "\n".join(f"# {l}" if l else "#" for l in lines) + "\n"


def _write(name: str, doc: dict, note_lines, dry_run: bool):
    path = os.path.join(OUT_DIR, name)
    text = (
        "# Auto-generated by scripts/gen_iccit_configs.py — do not hand-edit.\n"
        + _header(note_lines)
        + yaml.safe_dump(doc, sort_keys=False, default_flow_style=False)
    )
    if dry_run:
        print(f"--- {os.path.relpath(path, REPO_ROOT)} ---")
        print(text)
        return
    os.makedirs(OUT_DIR, exist_ok=True)
    with open(path, "w") as f:
        f.write(text)


def _mkunet_channel_mode_configs(dry_run: bool):
    for mode in CHANNEL_MODES:
        in_ch = effective_channel_count(mode, MODALITY)
        for ds in DATASETS:
            doc = {
                "compose": ["../../base.yaml", f"../../dataset/{ds}.yaml", f"../../model/mkunet/{MKUNET_SIZE}.yaml"],
                "model": {"in_channels": in_ch},
                "dataset": {"channel_mode": mode, "batch_size": 16},
                "logging": {"experiment_name": f"iccit_mkunet_{mode}_{ds}"},
            }
            _write(f"mkunet_{mode}_{ds}.yaml", doc, [
                f"F1 channel-mode grid — mk_unet_{MKUNET_SIZE}, {mode} ({in_ch}ch), {ds}.",
            ], dry_run)


def _mkunet_matched_configs(dry_run: bool):
    for mode in MATCHED_MODES:
        in_ch = effective_channel_count(mode, MODALITY)
        target_params = _mkunet_params(in_ch)
        match = _match_rgb_width(_mkunet_model_fn, [MKUNET_CHANNELS], target_params)
        if not match["within_tolerance"]:
            raise RuntimeError(
                f"gen_iccit_configs: no RGB width candidate matched {mode}'s "
                f"{target_params:,}-param target within {TOL:.0%} tolerance "
                f"(best: {match['relative_error']:.1%} error). Add a wider "
                f"MKUNET width candidate before generating this config."
            )
        for ds in DATASETS:
            doc = {
                "compose": ["../../base.yaml", f"../../dataset/{ds}.yaml", f"../../model/mkunet/{MKUNET_SIZE}.yaml"],
                "model": {"in_channels": 3, "channels": match["channels"]},
                "dataset": {"channel_mode": "m1", "batch_size": 16},
                "logging": {"experiment_name": f"iccit_mkunet_{mode}_matched_{ds}"},
            }
            _write(f"mkunet_{mode}_matched_{ds}.yaml", doc, [
                f"F2 capacity control — RGB (m1) width-matched to {mode}'s param count.",
                f"target_params={target_params:,} achieved_params={match['params']:,} "
                f"relative_error={match['relative_error']:.2%} channels={match['channels']}",
                "Record this match in the run manifest at training time "
                "(orchestration.manifest.RunManifest.record) — this comment is "
                "generation-time documentation only, not re-verified at run time.",
            ], dry_run)


def _mkunet_order_ablation_configs(dry_run: bool):
    for mode in ORDER_ABLATION_MODES:
        in_ch = effective_channel_count(mode, MODALITY)
        for ds in DATASETS:
            doc = {
                "compose": ["../../base.yaml", f"../../dataset/{ds}.yaml", f"../../model/mkunet/{MKUNET_SIZE}.yaml"],
                "model": {"in_channels": in_ch},
                "dataset": {"channel_mode": mode, "channel_build_order": "pre", "batch_size": 16},
                "logging": {"experiment_name": f"iccit_mkunet_{mode}_pre_{ds}"},
            }
            _write(f"mkunet_{mode}_pre_{ds}.yaml", doc, [
                f"F3 order ablation — {mode}, channel_build_order=pre (deliberately "
                "corrupts geometry/random-projection channels; C3's mechanism).",
            ], dry_run)


def _unet_generality_configs(dry_run: bool):
    m4_in_ch = effective_channel_count("m4", MODALITY)
    m4_target_params = _unet_params(m4_in_ch)
    m4_match = _match_rgb_width(_unet_model_fn, [UNET_FEATURES], m4_target_params)
    if not m4_match["within_tolerance"]:
        raise RuntimeError(
            f"gen_iccit_configs: no U-Net width candidate matched m4's "
            f"{m4_target_params:,}-param target within {TOL:.0%} tolerance."
        )

    for mode in ("m1", "m4", "m5"):
        in_ch = effective_channel_count(mode, MODALITY)
        for ds in DATASETS:
            doc = {
                "compose": ["../../base.yaml", f"../../dataset/{ds}.yaml"],
                "model": {"in_channels": in_ch},
                "dataset": {"channel_mode": mode, "batch_size": 16},
                "logging": {"experiment_name": f"iccit_unet_{mode}_{ds}"},
            }
            _write(f"unet_{mode}_{ds}.yaml", doc, [
                f"F5 generality — unet, {mode} ({in_ch}ch), {ds}."
            ], dry_run)

    for ds in DATASETS:
        doc = {
            "compose": ["../../base.yaml", f"../../dataset/{ds}.yaml"],
            "model": {"in_channels": 3, "features": m4_match["channels"]},
            "dataset": {"channel_mode": "m1", "batch_size": 16},
            "logging": {"experiment_name": f"iccit_unet_m4matched_{ds}"},
        }
        _write(f"unet_m4matched_{ds}.yaml", doc, [
            "F5 generality, capacity control — unet RGB (m1) width-matched to m4's param count.",
            f"target_params={m4_target_params:,} achieved_params={m4_match['params']:,} "
            f"relative_error={m4_match['relative_error']:.2%} features={m4_match['channels']}",
        ], dry_run)


def _external_colondb_eval_config(dry_run: bool):
    # One config, not per-mode/per-checkpoint: eval.py is run against
    # whichever training config produced the checkpoint under evaluation
    # (--config <same config used for training>), which already carries
    # the right channel_mode/in_channels — this fragment only needs to add
    # dataset.external: true and point at ColonDB. m1 here is a
    # placeholder default for standalone use (e.g. `python -m
    # datasets.stats` sanity checks against this file directly), not a
    # constraint on which mode a real evaluation run uses.
    doc = {
        "compose": ["../../base.yaml", "../../dataset/colondb.yaml", f"../../model/mkunet/{MKUNET_SIZE}.yaml"],
        "model": {"in_channels": 3},
        "dataset": {"channel_mode": "m1", "external": True},
        "logging": {"experiment_name": "iccit_external_colondb_eval"},
    }
    _write("external_colondb_eval.yaml", doc, [
        "C4 — ColonDB as a strictly external cohort, evaluated once via "
        "eval.py --allow-test-eval (get_standard_loaders()/get_fold_loaders() "
        "raise ExternalDatasetError; get_test_loader() works normally).",
        "In practice: compose this dataset/external override on top of "
        "whichever iccit training config produced the checkpoint being "
        "evaluated, so channel_mode/in_channels match that checkpoint — "
        "the m1 default here is only for standalone sanity checks.",
    ], dry_run)


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--dry-run", action="store_true", help="print configs, write nothing")
    args = parser.parse_args()

    _mkunet_channel_mode_configs(args.dry_run)
    _mkunet_matched_configs(args.dry_run)
    _mkunet_order_ablation_configs(args.dry_run)
    _unet_generality_configs(args.dry_run)
    _external_colondb_eval_config(args.dry_run)

    n = len(CHANNEL_MODES) * len(DATASETS) \
        + len(MATCHED_MODES) * len(DATASETS) \
        + len(ORDER_ABLATION_MODES) * len(DATASETS) \
        + 4 * len(DATASETS) \
        + 1
    action = "Would write" if args.dry_run else "Wrote"
    print(f"{action} {n} config(s) under {os.path.relpath(OUT_DIR, REPO_ROOT)}/")


if __name__ == "__main__":
    main()
